name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy 

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      DEPLOY_USER: "${{ secrets.DEPLOY_USER }}"
      ACCESS_KEY: ${{ secrets.YCLOUD_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.YCLOUD_SECRET_KEY }}
      TF_VAR_ycloud_token: ${{ secrets.YCLOUD_TOKEN }}
      TF_VAR_ycloud_id: ${{ secrets.YCLOUD_ID }}
      TF_VAR_ycloud_folder_id: ${{ secrets.YCLOUD_FOLDER_ID }}
      TF_VAR_ycloud_zone: ${{ secrets.YCLOUD_ZONE }}
      TF_VAR_ycloud_s3_name: ${{ secrets.YCLOUD_S3_NAME }}
      TF_VAR_ycloud_vm_ssh_key: ${{ secrets.YCLOUD_SSH_KEY }}
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -var-file="variables.tfvars"

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -var-file="variables.tfvars" -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -var-file="variables.tfvars" -auto-approve
